version: "3.7"
services:
  app:
    container_name: cleezy-app-dev
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - --database-file-path=/tmp/urldatabase.db
      - --qr-code-cache-path=/tmp/
      - --qr-code-cache-state-file=/tmp/cleezy-state
      - --qr-code-base-url=http://localhost:8000/find
      - --port=8000
      - --qr-code-center-image-path=/app/assets/SCE_logo.png
      - -vvv
    ports:
      - 8000:8000
    volumes:
      - cleezy_data_dev:/tmp/
      - ./server.py:/app/server.py
      - ./modules:/app/modules
      - ./assets:/app/assets
    environment:
      - WATCHFILES_FORCE_POLLING=true
  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

volumes:
  cleezy_data_dev:
